<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Beacon.HostAgent.Contracts\Beacon.HostAgent.Contracts.csproj" />
    <ProjectReference Include="..\Beacon.Platform.Windows\Beacon.Platform.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Beacon.HostAgent.Tests" />
  </ItemGroup>

</Project>
