plugins {
    id 'com.android.library'
}

android {
    namespace 'dev.beacon.streaming.moonlight'
    compileSdk 35
    ndkVersion '27.0.12077973'

    defaultConfig {
        minSdk 26

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_static'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
